language: cpp

sudo: false

git:
  depth: 1

cache:
  - apt
  - directories:
      - $HOME/cmake
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages: 
      - ['g++-5', 'g++-4.9', 'g++-4.8']
      - ['clang-3.6']
      - ['doxygen', 'graphviz', 'texlive-binaries']
      #cannot install more than one clang.
before_install:
  - export CC=$EXPORT_CC CXX=$EXPORT_CXX

script:
  #docs
  #- doxygen
  #cmake 
  - mkdir -p $HOME/cmake
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz --no-check-certificate
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.1.3-Linux-x86_64/bin/cmake
  #fuzzylite
  #release
  - cd fuzzylite
  - mkdir -p release
  - cd release
  - $CMAKE_CMD .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFL_BACKTRACE=ON -DFL_USE_FLOAT=$FL_USE_FLOAT -DFL_CPP11=$FL_CPP11 -DFL_BUILD_TESTS=OFF
  - make all test
  - cd ..
  #debug
  - mkdir -p debug
  - cd debug
  - $CMAKE_CMD .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DFL_BACKTRACE=ON -DFL_USE_FLOAT=$FL_USE_FLOAT -DFL_CPP11=$FL_CPP11 -DFL_BUILD_TESTS=OFF
  - make all test
  - cd ..


matrix:
  exclude:
    - env: ignore=this

  include:

##clang-3.7
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.7 FL_CPP11=OFF FL_USE_FLOAT=OFF
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.7 FL_CPP11=OFF FL_USE_FLOAT=ON
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.7 FL_CPP11=ON FL_USE_FLOAT=OFF
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.7 FL_CPP11=ON FL_USE_FLOAT=ON

#clang-3.6
    - os: linux
      compiler: clang
      env: EXPORT_CXX=clang++-3.6 FL_CPP11=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: EXPORT_CXX=clang++-3.6 FL_CPP11=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: EXPORT_CXX=clang++-3.6 FL_CPP11=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: EXPORT_CXX=clang++-3.6 FL_CPP11=ON FL_USE_FLOAT=ON

##clang-3.5
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.5 FL_CPP11=OFF FL_USE_FLOAT=OFF
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.5 FL_CPP11=OFF FL_USE_FLOAT=ON
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.5 FL_CPP11=ON FL_USE_FLOAT=OFF
    #- os: linux
      #compiler: clang
      #env: EXPORT_CXX=clang++-3.5 FL_CPP11=ON FL_USE_FLOAT=ON


#g++-5
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-5 FL_CPP11=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-5 FL_CPP11=OFF FL_USE_FLOAT=ON 
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-5 FL_CPP11=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-5 FL_CPP11=ON FL_USE_FLOAT=ON 

#g++-4.9
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.9 FL_CPP11=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.9 FL_CPP11=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.9 FL_CPP11=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.9 FL_CPP11=ON FL_USE_FLOAT=ON

#g++-4.8
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.8 FL_CPP11=OFF FL_USE_FLOAT=OFF 
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.8 FL_CPP11=OFF FL_USE_FLOAT=ON 
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.8 FL_CPP11=ON FL_USE_FLOAT=OFF 
    - os: linux
      compiler: g++
      env: EXPORT_CXX=g++-4.8 FL_CPP11=ON FL_USE_FLOAT=ON

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
